name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v18
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: sudo apt install drawio
      - run: pip install mkdocs
      - run: pip install mkdocs-jupyter
      - run: pip install python-markdown-math
      - run: nix build .#mkdocs-generator
      - run: ./result/bin/mkdocs-generator
      - run: mkdocs gh-deploy --force --clean --verbose
