name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: cachix/install-nix-action@v18
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: nix run .#mkdocs-generator
      - run: mkdocs gh-deploy --force --clean --verbose
